version: '3.2'

services:

  frontend:
    build: frontend
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./:/app

  backend:
    build: backend
    restart: unless-stopped
    ports:
      - 81:80
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./:/app

  mysql:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=fpassword
      - MYSQL_DATABASE=management
      - MYSQL_USER=management
      - MYSQL_PASSWORD=tpassword

  pma:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    environment:
      - PMA_HOST=mysql
    ports:
      - 89:80
    depends_on:
      - mysql



  